# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testsuite.ui'
#
# Created: Tue May 20 23:43:42 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TestSuite(object):
    def setupUi(self, TestSuite):
        TestSuite.setObjectName(_fromUtf8("TestSuite"))
        TestSuite.resize(647, 508)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("images/list_accept.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TestSuite.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(TestSuite)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonAdd = QtGui.QPushButton(self.groupBox)
        self.buttonAdd.setObjectName(_fromUtf8("buttonAdd"))
        self.horizontalLayout.addWidget(self.buttonAdd)
        self.buttonNew = QtGui.QPushButton(self.groupBox)
        self.buttonNew.setObjectName(_fromUtf8("buttonNew"))
        self.horizontalLayout.addWidget(self.buttonNew)
        self.buttonSave = QtGui.QPushButton(self.groupBox)
        self.buttonSave.setObjectName(_fromUtf8("buttonSave"))
        self.horizontalLayout.addWidget(self.buttonSave)
        self.buttonLoad = QtGui.QPushButton(self.groupBox)
        self.buttonLoad.setObjectName(_fromUtf8("buttonLoad"))
        self.horizontalLayout.addWidget(self.buttonLoad)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listTestCollection = QtGui.QListWidget(self.groupBox)
        self.listTestCollection.setDragEnabled(True)
        self.listTestCollection.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.listTestCollection.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listTestCollection.setObjectName(_fromUtf8("listTestCollection"))
        self.verticalLayout.addWidget(self.listTestCollection)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.buttonExecute = QtGui.QPushButton(self.groupBox_4)
        self.buttonExecute.setObjectName(_fromUtf8("buttonExecute"))
        self.horizontalLayout_2.addWidget(self.buttonExecute)
        self.buttonExecuteAll = QtGui.QPushButton(self.groupBox_4)
        self.buttonExecuteAll.setObjectName(_fromUtf8("buttonExecuteAll"))
        self.horizontalLayout_2.addWidget(self.buttonExecuteAll)
        self.buttonStop = QtGui.QPushButton(self.groupBox_4)
        self.buttonStop.setObjectName(_fromUtf8("buttonStop"))
        self.horizontalLayout_2.addWidget(self.buttonStop)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.sliderSpeed = QtGui.QSlider(self.groupBox_2)
        self.sliderSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSpeed.setObjectName(_fromUtf8("sliderSpeed"))
        self.horizontalLayout_4.addWidget(self.sliderSpeed)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.textBrowserLog = QtGui.QTextBrowser(self.groupBox_3)
        self.textBrowserLog.setObjectName(_fromUtf8("textBrowserLog"))
        self.verticalLayout_4.addWidget(self.textBrowserLog)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        TestSuite.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(TestSuite)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 647, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        TestSuite.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(TestSuite)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        TestSuite.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(TestSuite)
        QtCore.QMetaObject.connectSlotsByName(TestSuite)

    def retranslateUi(self, TestSuite):
        TestSuite.setWindowTitle(_translate("TestSuite", "TestSuite", None))
        self.groupBox.setTitle(_translate("TestSuite", "Test Collection", None))
        self.buttonAdd.setText(_translate("TestSuite", "Add", None))
        self.buttonNew.setText(_translate("TestSuite", "New", None))
        self.buttonSave.setText(_translate("TestSuite", "Save", None))
        self.buttonLoad.setText(_translate("TestSuite", "Load", None))
        self.groupBox_4.setTitle(_translate("TestSuite", "Execution", None))
        self.buttonExecute.setText(_translate("TestSuite", "Execute", None))
        self.buttonExecuteAll.setText(_translate("TestSuite", "Execute All", None))
        self.buttonStop.setText(_translate("TestSuite", "Stop", None))
        self.groupBox_2.setTitle(_translate("TestSuite", "Options", None))
        self.label_2.setText(_translate("TestSuite", "Execution Speed:", None))
        self.label_3.setText(_translate("TestSuite", "Slow", None))
        self.label_4.setText(_translate("TestSuite", "Fast", None))
        self.groupBox_3.setTitle(_translate("TestSuite", "Log", None))
        self.menuFile.setTitle(_translate("TestSuite", "File", None))

